---
- name: install nfs pakcages
  yum: name=nfs-utils,libnfsidmap state=latest

- name: stop nfs
  service: name=nfs state=stopped

- name: stop rpcbind
  service: name=rpcbind state=stopped

- name: unmount existing volumes
  shell: umount /mnt/volume || true

- name: create a ext4 filesystem on /dev/vdb
  filesystem: fstype=ext4 dev=/dev/vdb

- name: create mount directory
  file: name=/mnt/volume state=directory

- name: mount storage volume
  mount: name=/mnt/volume src=/dev/vdb fstype=ext4 state=mounted

- name: bind mount to export directory
  mount: name=/export src=/mnt/volume fstype=none opts=bind state=mounted

- name: install /etc/exports
  template: src=exports dest=/etc/exports mode=0644

- name: start rpcbind
  service: name=rpcbind state=started

- name: create /mnt/volume/home
  file: path=/mnt/volume/home state=directory

- name: create /mnt/volume/exchange
  file: path=/mnt/volume/exchange state=directory

- name: create home directories
  file: path=/mnt/volume/home/{{ item }} state=directory group=100 owner=1000 recurse=yes
  with_items:
  - "{{ jupyterhub_admins }}"
  - "{{ jupyterhub_users }}"
  tags:
  - add_users

- name: create exchange directories
  file: path=/mnt/volume/exchange/{{ item }}/accy state=directory group=100 owner=1000 recurse=yes
  with_items:
  - "{{ jupyterhub_admins }}"
  - "{{ jupyterhub_users }}"
  tags:
  - add_users

- name: create exchange/inbound directories
  file: path=/mnt/volume/exchange/{{ item }}/accy/inbound state=directory group=root owner=root mode=0733 recurse=yes
  with_items:
  - "{{ jupyterhub_admins }}"
  - "{{ jupyterhub_users }}"
  tags:
  - add_users

- name: create exchange/outbound directories
  file: path=/mnt/volume/exchange/{{ item }}/accy/outbound state=directory group=root owner=root mode=0755 recurse=yes
  with_items:
  - "{{ jupyterhub_admins }}"
  - "{{ jupyterhub_users }}"
  tags:
  - add_users

- name: create shared directory
  file: path=/mnt/volume/shared state=directory group=root owner=root recurse=yes

- name: git clone accy570 repo
  git: repo=https://github.com/ui-datascience/accy570-fa16 dest=/mnt/volume/shared/accy570-fa16

- name: git clone accy571 repo
  git: repo=https://github.com/ui-datascience/accy571-fa16 dest=/mnt/volume/shared/accy571-fa16

- name: start nfs-server
  service: name=nfs state=started

