---
- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  roles:
  - common
  tags:
  - common

- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - docker
  tags:
  - docker

- hosts:
  - jupyterhub_host
  vars_files:
  - users.yml
  - vars.yml
  roles:
  - nfs_server
  tags:
  - nfs

- hosts:
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - nfs_client
  tags:
  - nfs

#- hosts:
#  - jupyterhub_host
#  vars_files:
#  - vars.yml
#  roles:
#  - duplicity
#  tags:
#  - duplicity

- hosts:
  - jupyterhub_host
  vars_files:
  - vars.yml
  roles:
  - consul_server
  tags:
  - consul

- hosts:
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - consul_client
  tags:
  - consul

- hosts:
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - singleuser
  tags:
  - singleuser

- hosts: 
  - jupyterhub_host
  vars_files:
  - users.yml
  - vars.yml
  roles:
  - hub
  - cron
  tags:
  - hub

- hosts:
  - proxy
  vars_files:
  - vars.yml
  roles:
  - proxy
  tags:
  - proxy

