---
- hosts:
  - proxy
  - jupyterhub_host
  roles:
  - common

- hosts:
  - proxy
  - jupyterhub_host
  roles:
  - docker

- hosts:
  - proxy
  roles:
  - proxy

- hosts: jupyterhub_host
  vars_files:
  - users.yml
  roles:
  - hub
