---
- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  roles:
  - common

- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  roles:
  - docker

- hosts:
  - proxy
  roles:
  - proxy

- hosts:
  - jupyterhub_host
  roles:
  - consul_server

- hosts:
  - jupyterhub_nodes
  roles:
  - consul_client

- hosts: 
  - jupyterhub_host
  vars_files:
  - users.yml
  roles:
  - hub
