swarm:
    image: swarm
    restart: always
#    command: manage -H 127.0.0.1:{{ docker_server_port }} --tlsverify --tlscacert={{ docker_tls_path }}/ca.pem --tlscert={{ docker_tls_path }}/cert.pem --tlskey={{ docker_tls_path }}/key.pem file:///root/.swarm/cluster
    command: manage "consul://{{ private_ip }}:8500/swarm"
    volumes:
      - "{{ docker_tls_path }}:{{ docker_tls_path }}"
    ports:
      - "{{ docker_server_port }}:2375"

jupyterhub:
    build: /srv/jupyterhub
    restart: always
    environment:
      HUB_IP: "{{ private_ip }}"
#      DOCKER_TLS_CERT: "{{ docker_tls_path }}/cert.pem"
#      DOCKER_TLS_KEY: "{{ docker_tls_path }}/key.pem"
    ports:
      - "{{ private_ip }}:8000:8000"
      - "{{ private_ip }}:8081:8081"
    volumes:
      - /srv/jupyterhub_users:/srv/jupyterhub_users
      - "{{ docker_tls_path }}:{{ docker_tls_path }}"
    links:
      - swarm
