jupyterhub:
    build: /srv/jupyterhub
    restart: always
    ports:
      - "{{ ansible_host }}:8000:8000"
      - "{{ ansible_host }}:8081:8081"
    volumes:
      - /srv/jupyterhub_users:/srv/jupyterhub_users

