---
- name: create the singleuser directory
  file: path=/srv/singleuser state=directory

- name: copy the Dockerfile to the singleuser directory
  template: src=Dockerfile.singleuser.j2 dest=/srv/singleuser/Dockerfile

- name: copy singleuser.sh to the singleuser directory
  copy: src=singleuser.sh dest=/srv/singleuser/singleuser.sh

- name: copy logo.png
  copy: src=logo.png dest=/srv/singleuser/logo.png

- name: copy custom.css
  copy: src=custom.css dest=/srv/singleuser/custom.css

- name: pull lcdm/accy image
  shell: docker pull lcdm/accy

- name: build singleuser image
  shell: docker build -t singleuser /srv/singleuser
