---
- name: create the singleuser directory
  file: path=/srv/singleuser state=directory

- name: copy the Dockerfile to the singleuser directory
  template: src=Dockerfile.singleuser.j2 dest=/srv/singleuser/Dockerfile

- name: copy nbgrader_config.py
  copy: src=nbgrader_config.py dest=/srv/singleuser/nbgrader_config.py

- name: pull lcdm/accy image
  shell: docker pull lcdm/accy:latest

- name: build singleuser image
  shell: docker build -t singleuser /srv/singleuser
