- name: stop and remove running singleuser containers
  docker:
    state: absent
    image: edwardjkim/singleuser

- name: create the singleuser directory
  file: path=/srv/singleuser state=directory

- name: copy the Dockerfile to the singleuser directory
  template:
    src: Dockerfile.j2
    dest: /srv/singleuser/Dockerfile

- name: copy singleuser.sh to the singleuser directory
  copy:
    src: singleuser.sh
    dest: /srv/singleuser/singleuser.sh

- name: build edwardjkim/singleuser image
  shell: docker build -t edwardjkim/singleuser /srv/singleuser
